Antiaffinity with zone topology for high availability
apache/pulsar-helm-chart pull request #127
Opened 2021-06-10 21:58 UTC by sdwerwed

### Motivation

There is no option in the current helm chart to make the pulsar high available. With this pull request, we can make some of the pulsar components highly available (multiAZ support). This is usually a requirement by many companies and I believe it will help many people that are facing this limitation. This version is backwards compatible, the default values are the same. It is tested and works as expected, pods can be scheduled in different availability zones if `<component>.affinity.anti_affinity_topology.zone.enabled: true`

### Modifications

I have added an extra option in the anti-affinity section for multiAZ support that is disabled by default. Made the weight from static value to variable (default is same), so users can adjust the weight in case they want to use both `host` and `zone` anti-affinity 

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

2021-06-10 22:28 UTC, sdwerwed commented
As I am a first-time contributor, can a maintainer run the pipelines, please?

2021-12-22 16:59 UTC, sdwerwed commented
Hello @wolfstudy, @sijie, can you have a look at this PR, let me know if any other action is required from my side.

2022-01-20 06:30 UTC, lhotari approved these changes
Good work @sdwerwed . Thank you for the contribution.

2022-01-20 06:37 UTC, sijie commented
@sdwerwed: I think the zone affinity would work for stateless components. I don't think it will work well for stateful components. Because the location of bookie and zookeeper pods will be bound to the location of EBS volumes. Also, even you are able to place bookies across different zones. But you don't configure the rack information, so bookkeeper can potentially place two same copies in the pods running in the same zone.

Hence I believe the solution is incomplete. If we merge this, it will cause confusion to people and let them believe it is a "complete" solution.

2022-01-20 06:37 UTC, sijie requested changes
would love to see the comment is addressed first.

2022-01-20 20:14 UTC, michaeljmarshall commented
> @sdwerwed: I think the zone affinity would work for stateless components. I don't think it will work well for stateful components. Because the location of bookie and zookeeper pods will be bound to the location of EBS volumes.

To add some AWS context, EBS volumes are restricted to a single availability zone within a region. Once a bookie gets an EBS volume, it cannot be migrated to another AZ. I haven't looked closely at this PR, but we'll need to make sure that it works for upgrading existing clusters that do not comply with the anti-affinity policy.

> Also, even you are able to place bookies across different zones. But you don't configure the rack information, so bookkeeper can potentially place two same copies in the pods running in the same zone. 

I agree that this could be misleading. We could mitigate the shortcoming with documentation, though. Also, this feature can work without configuring rack awareness. For example, if your ack quorum is greater than the number of bookies in a single AZ, you'll know that your writes are spread across multiple AZs and are therefore HA. This isn't as good as configuring rack awareness, but it is probably better than random bookie scheduling.

2022-03-21 16:18 UTC, sdwerwed commented
@sijie 

> I think the zone affinity would work for stateless components. I don't think it will work well for stateful components. Because the location of bookie and zookeeper pods will be bound to the location of EBS volumes. 

This is a known limitation of AWS and probably Azure too, however, the default value is not multi az, if an enginner would like to make it multi az can do it manually with additional steps, not sure if we can handle that in the helm chart anyway, we could document that or if you have another idea how we could make it fully functional with helm let me know.

> But you don't configure the rack information, so bookkeeper can potentially place two same copies in the pods running in the same zone.

I think I miss some context here as I did not get what is the issue, what do you mean to configure rack information? Could you give me some sources to read about it so I can suggest a solution?

2023-03-01 21:17 UTC, frankjkelly commented
Any update on this? Would be great to help make Pulsar HA

2023-04-15 16:32 UTC, sdwerwed commented
Closing this as got very old and need maintenance

2023-04-15 16:32 UTC, closed without merging