automate initialize
apache/pulsar-helm-chart pull request #138
Opened 2021-07-15 11:53 UTC by valeriano-manassero

Fixes #<xyz>

### Motivation

Having `initialize` value that must be manually set is prone to human error, there is a risk of running init again forcing the need of a rollback.

### Modifications

Using Helm capability to understand if it's an install or upgrade we can avoid to launch init when not needed.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

2021-08-21 00:23 UTC, sijie approved these changes

2021-09-14 07:38 UTC, valeriano-manassero commented
This is going to be merged?

2022-01-05 07:43 UTC, lhotari requested changes

2022-01-05 07:43 UTC, lhotari commented on charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
> +{{- if .Release.IsInstall }}
I'd suggest keeping backwards compatibility. 
```suggestion
{{- if or .Release.IsInstall .Values.initialize }}
```
The benefit of this is that the metadata initialization job can be created on demand when needed. I have been using this in test environments. It's possible to clear the persistent state of the cluster by scaling stateful sets to 0, deleting PVCs and doing a deployment with `--set initialize=true`.

2022-01-05 07:43 UTC, lhotari commented on charts/pulsar/templates/pulsar-cluster-initialize.yaml
> +{{- if .Release.IsInstall }}
```suggestion
{{- if or .Release.IsInstall .Values.initialize }}
```

2022-01-05 07:43 UTC, lhotari commented on charts/pulsar/values.yaml
> -## Set to true on install
please revert this change to keep backwards compatibility.

2022-01-05 11:02 UTC, lhotari approved these changes
LGTM

2022-01-05 11:42 UTC, lhotari commented
@valeriano-manassero Thank you for the contribution. Would it be also possible to update README.md in this PR and remove the instructions of using `--set initialize=true` when doing the installation?

2022-01-05 13:59 UTC, valeriano-manassero commented
> @valeriano-manassero Thank you for the contribution. Would it be also possible to update README.md in this PR and remove the instructions of using `--set initialize=true` when doing the installation?

done

2022-01-05 14:04 UTC, lhotari approved these changes

2022-01-05 14:08 UTC, merged