[Istio] Kill istio proxy when container has completed
apache/pulsar-helm-chart pull request #181
Opened 2021-11-29 20:07 UTC by frankjkelly

### Motivation

When using Istio sidecars they keep running even when a Kubernetes job has completed.
For example
```
$ kubectl get pods | grep pulsar | grep init
platform-pulsar-bookkeeper-init-vwp6v                             1/2     NotReady    0          13d
platform-pulsar-pulsar-init-c2c72                                 1/2     NotReady    0          13d
```

### Modifications

* Added a new Helm chart value `Istio.enabled` (default: false)
* In both Kubernetes jobs added a call to Istio to kill the Istio proxy once the container job has completed

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

2021-12-13 23:52 UTC, sijie requested changes

2021-12-13 23:52 UTC, sijie commented on charts/pulsar/templates/bookkeeper-cluster-initialize.yaml
> +            {{- if .Values.istio.enabled }}
I would suggest a different approach:

Can you just introduce a setting called `extraInitCommand`? So you can include this in the init container. Then you can add this command to your values file. This provides better extensibility to the helm chart.

2022-01-04 16:09 UTC, sijie approved these changes

2022-01-04 16:32 UTC, michaeljmarshall approved these changes

2022-01-04 21:02 UTC, frankjkelly commented
Helm chart 2.7.7 was already released. See
https://github.com/apache/pulsar-helm-chart/releases/tag/pulsar-2.7.7
and
https://pulsar.apache.org/charts/index.yaml

2022-01-04 21:57 UTC, michaeljmarshall approved these changes
LGTM

2022-01-05 13:58 UTC, lhotari approved these changes
LGTM

2022-01-05 14:24 UTC, merged