Update ingress api version, extension/v1beta1 will not be supported i…
apache/pulsar-helm-chart pull request #183
Opened 2021-12-02 11:29 UTC by wangshu3000

…n new k8s version, this change keep backward compatibility for lower kubernetes version 

Fixes #157

### Motivation

The ingress api extensions/v1beta1 version will not be supported in k8s version 1.22+, need to update to new networking.k8s.io/v1.
This PR also keep support for old k8s version, to provide enough compatibility.

### Modifications

Updated the api version for below 4 components:
1. dashboard-ingress
2. grafana-ingress
3. proxy-ingress
4. pulsar-manager-ingress

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

2021-12-14 02:12 UTC, wangshu3000 commented
Could anybody in the team please review this PR? Thanks.

2022-01-03 21:31 UTC, lhotari approved these changes
Good work!

2022-01-03 22:02 UTC, michaeljmarshall requested changes
Great work @wangshu3000! I think it might make sense to modify the conditionals in the PR. Let me know what you think. Otherwise, this looks good to me.

2022-01-03 22:02 UTC, michaeljmarshall commented on charts/pulsar/templates/dashboard-ingress.yaml
> +{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
@wangshu3000 - do you have a reference that documents `GitVersion`? I don't see that in the helm documentation (https://helm.sh/docs/chart_template_guide/builtin_objects/).

I think we should prefer the logic described in this stack overflow answer: https://stackoverflow.com/a/66191437. Essentially, we can inspect the `APIVersion` to see if the api has `networking.k8s.io/v1` and branch accordingly.

2022-01-03 22:03 UTC, michaeljmarshall commented
@lhotari - do you know why the CI checks wouldn't have run for this PR? I haven't seen that happen before.

2022-01-04 00:46 UTC, wangshu3000 commented on charts/pulsar/templates/dashboard-ingress.yaml
> +{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
@michaeljmarshall  Thanks for the feedback. 
Looks like they changed the doc. I saw this from some examples of helm repo. Looks like it's been deprecated. The new value should be Capabilities.KubeVersion.Version

There is one problem with .Capabilities.APIVersions.Has
When someone use helm template command. It'll lock the kubernetes version to latest version in helm. So if they use new helm version 3.7+, there would always has the new api version even already specify the old kubenetes version in parameter. So the generated template yaml will have the new api version, when applying those yaml files, they will be failed in old kubernetes cluster. 

I think maybe we should change to KubeVersion.Version as the KubeVersion.GitVersion has been deprecated.

Please let me know if this make sense. 

Thanks.

2022-01-04 00:51 UTC, wangshu3000 commented on charts/pulsar/templates/dashboard-ingress.yaml
> +{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
https://github.com/argoproj/argo-cd/issues/3594
This is the issue for your reference.
There are some discussion around this.

2022-01-04 05:24 UTC, michaeljmarshall commented on charts/pulsar/templates/dashboard-ingress.yaml
> +{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
@wangshu3000 that definitely makes sense. I didn't know about the feature's shortcoming, thanks for sharing. Otherwise, do you need to update it to `KubeVersion.GitVersion` to `KubeVersion.Version`? We also need to figure out why CI hasn't run for this PR.

2022-01-04 05:27 UTC, wangshu3000 commented on charts/pulsar/templates/dashboard-ingress.yaml
> +{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
@michaeljmarshall  ok. let me do it.

2022-01-04 06:48 UTC, michaeljmarshall approved these changes
LGTM. @wangshu3000 - looks like the tests ran against this latest PR, so that's good too.

2022-01-04 06:53 UTC, merged